# Tipos de Ave
TIPOS_AVE = [
    'FRANGO',
    'GALINHA LEVE',
    'GALINHA MATRIZ',
    'GALINHA VERMELHA',
    'GALO'
]

# Lista de Motoristas
MOTORISTAS = [
    'ALEXANDRE DE JESUS JOÃO',
    'CARLOS LAZARO DOS SANTOS AGUIAR',
    'CLAUDIO FERREIRA SALOMÃO', 
    'EDIMILTON SILVA SANTOS',
    'FABRICIO SANTOS DE SÁ',
    'GILSON DOS SANTOS GONÇALVES',
    'HIGOR DA SILVA ROSA',
    'MILTON CANDIDO EVANGELISTA ',
    'SADRAQUE RAMOS SALES',
    'WILISSES SANTIAGO'
]

# Lista de Transportadoras
TRANSPORTADORAS = [
    'Ellen Transportes',
    'Terceirizado'
]

# Lista de Placas Ellen
PLACAS_ELLEN = [
    'PLACA 1',
    'PLACA 2',
    'PLACA 3'
]

# Valores por KM
VALORES_KM = {
    'FRANGO': 2.50,
    'GALINHA': 2.75,
    'PERU': 3.00
}

# Status do Frete
STATUS_FRETE = [
    'A_PAGAR',
    'INCLUSO',
    'PAGO',
    'CANCELADO'
]

# Estados do Brasil
ESTADOS_BRASIL = [
    'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA',
    'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN',
    'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO'
]

# Número inicial para cargas
NUMERO_INICIAL_CARGA = 5040

# Lista de Produtores
PRODUTORES = [
    "AJL - AGRONEGOCIO JOSIDITH LTDA",
    "ALESSANDRA BERGER",
    "ANACLETO ROSA FONSECA",
    "ANTONIO CARLOS VASCONCELOS COSTA E OUTROS",
    "ANTÔNIO VENTURINI E OUTROS",
    "AlVINO JOSÉ HUGUININ",
    "AVIARIO SANTO ANTONIO LTDA",
    "AVIARIO SANTO ANTONIO LTDA C2",
    "AVIPLUMA S/A",
    "AVIVAR ALIMENTOS S/A",
    "BIANCA SOARES DE OLIVEIRA",
    "BL CONSERVAS E ALIMENTOS LTDA",
    "BONASA ALIMENTOS LTDA",
    "CARLOS MAGNUS CALIMAN BERGER",
    "CAROLINA INGLE KERCKHOFF",
    "CELIO BORCHARDT",
    "CLAUDIANO VESPER",
    "CLEIDE HUMBERTO DE OLIVEIRA",
    "COMPANHIA DE ALIMENTOS UNIAVES",
    "COOPERATIVA AGROPECUARIA CENTRO SERRANA",
    "CRISTIANO RAPOSO SCITOWICZ",
    "EDSON JASTROW",
    "EDUARDO STUHR",
    "ERASMO BERGER",
    "ERASMO SCHWANZ",
    "FABIO BOLDT",
    "FABIO TESCH",
    "FABRICIO GUILHERME",
    "FABRICIO OLIVEIRA FORNALLE",
    "FELLIPE ALEXANDRE VENTURINI",
    "FERNANDO HENRIQUE GONÇALVES MELO",
    "FLAVIO DA SILVA FERRÃO E OUTROS",
    "FLORENCIO A. BERGER NETO",
    "FRANGO DOURADO COMERCIO E INDUSTRIA DE",
    "FREDOLIN BOLDT",
    "FREDY SEIDLER BERGER",
    "GERALDO MAGELA DE OLIVEIRA",
    "GERSON MARQUARDT",
    "GIOVANI CATELAN",
    "GISLENE GUMS",
    "GLOBOAVES SAO PAULO AGROAVICOLA LTDA",
    "GRANJA ALEXAVES LTDA",
    "GRANJA BRASILIA AGROINDUSTRIAL AVICOLA",
    "GRANJAS CARAMURU",
    "GRANJA LOYOLA LTDA",
    "GRANJA RIO MINAS LTDA",
    "GRANJA SALOME LTDA",
    "GRAZIELLE GUMS",
    "GRUPO MANTIQUEIRA LTDA",
    "HALECSON STINGUEL",
    "HELMAR GUMS",
    "HERCULES MARIN",
    "IGOR INGLE KERCKHOFF",
    "INACIO ERDMANN",
    "INDUSTRIA E COMERCIO DE OVOS INDAIA LTDA",
    "ISABELA GONÇALVES CABRAL E OUTROS",
    "IVAN BOLDT E OUTROS",
    "IVAN HELMER",
    "IZIDORO KRAUSE",
    "JEFERSON LUIZ MARIM",
    "JESEBEL FOESCH BOTELHO",
    "JOAQUIM SCHAEFFER",
    "JORGE GALACHO",
    "JOSE DE PAULO GRYSCHEK",
    "KARINA BERGER",
    "MANFREDO KRUGER",
    "MARCELO MINORU MAKI",
    "MARCIO LEMKE",
    "MARCOS ANTONIO PLASTER",
    "MARCOS LEMKE",
    "MARLENE RAPOSO SCISTOWICZ",
    "MARUTANI ALIMENTOS EIRELI",
    "MAURICEA ALIMENTOS DO NORDESTE LTDA",
    "MURILO CARLOS PAIVA CARVALHO JUNIOR",
    "NUBIA KRUGER LAUVERS",
    "NUTRIZA AGROINDUSTRIAL DE ALIMENTOS S/A",
    "OVOS UP LTDA",
    "PLANALTO OVOS LTDA",
    "POLE ALIMENTOS LTDA",
    "POLE GRANJA PARAISO POLE ALIMENTOS LTDA",
    "POLE MORUM",
    "PRODUTOR RURAL PARA HOMOLOGAÇÃO",
    "PRODUTORA DE OVOS JOSIDITH - EIRELI",
    "PROTEINORTE ALIMENTOS S/A",
    "RADIL ALIMENTOS LTDA",
    "RAFAEL BOZANI PIMENTEL",
    "RAFAEL FRIEDRICH E OUTROS",
    "RAFAEL JUNIOR BESSAS DO COUTO E OUTROS",
    "RENAN BERGER",
    "RENILDO TRESMANN",
    "RIO BRANCO ALIMENTOS S/A",
    "RIVELLI",
    "RODRIGO FRIEDRICH",
    "ROGERIO STANGE",
    "RONAN JOSE COSME",
    "RONEY BESSAS DO COUTO E OUTRO",
    "SEARA ALIMENTOS LTDA",
    "SIDNEY BOLINA AZEVEDO FILHO",
    "SILVANO RUIVO DE OLIVEIRA",
    "SOMAI NORDESTE S/A",
    "TANIA BUSS REPKE E OUTROS",
    "TIAGO ROSSI",
    "UNIÃO DE FAZENDAS AGROINDUSTRIAIS S/A",
    "VIBRA AGROINDUSTRIAL SA",
    "VIVIANE MAZZETTO GUIMARÃES",
    "VOLKMAR BERGER",
    "WALDEMAR LEMKE",
    "WALDEMIRO BERGER",
    "WEVERTON JOÃO ESPINDULA E OUTROS",
    "WILSON STOBERL"
]

