"""Migracao inicial

Revision ID: 622200274f91
Revises: 
Create Date: 2025-01-23 09:52:56.003710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622200274f91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mensagens_destinatario', type_='foreignkey')
        batch_op.drop_constraint('fk_mensagens_remetente', type_='foreignkey')
        batch_op.create_foreign_key('fk_mensagens_destinatario_new', 'usuarios', ['destinatario_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_mensagens_remetente_new', 'usuarios', ['remetente_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notificacoes_usuario', type_='foreignkey')
        batch_op.drop_constraint('fk_notificacoes_carga', type_='foreignkey')
        batch_op.create_foreign_key('fk_notificacoes_carga_new', 'cargas', ['carga_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_notificacoes_usuario_new', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_solicitacoes_analisado', type_='foreignkey')
        batch_op.drop_constraint('fk_solicitacoes_solicitado', type_='foreignkey')
        batch_op.drop_constraint('fk_solicitacoes_verificado', type_='foreignkey')
        batch_op.create_foreign_key('fk_solicitacoes_analisado_new', 'usuarios', ['analisado_por_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_solicitacoes_solicitado_new', 'usuarios', ['solicitado_por_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_solicitacoes_verificado_new', 'usuarios', ['verificado_por_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('senha_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_column('usuario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario', sa.VARCHAR(length=50), server_default=sa.text("('')"), nullable=False))
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('senha_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_solicitacoes_verificado_new', type_='foreignkey')
        batch_op.drop_constraint('fk_solicitacoes_solicitado_new', type_='foreignkey')
        batch_op.drop_constraint('fk_solicitacoes_analisado_new', type_='foreignkey')
        batch_op.create_foreign_key('fk_solicitacoes_verificado', 'usuarios', ['verificado_por_id'], ['id'])
        batch_op.create_foreign_key('fk_solicitacoes_solicitado', 'usuarios', ['solicitado_por_id'], ['id'])
        batch_op.create_foreign_key('fk_solicitacoes_analisado', 'usuarios', ['analisado_por_id'], ['id'])

    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notificacoes_usuario_new', type_='foreignkey')
        batch_op.drop_constraint('fk_notificacoes_carga_new', type_='foreignkey')
        batch_op.create_foreign_key('fk_notificacoes_carga', 'cargas', ['carga_id'], ['id'])
        batch_op.create_foreign_key('fk_notificacoes_usuario', 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.drop_constraint('fk_mensagens_remetente_new', type_='foreignkey')
        batch_op.drop_constraint('fk_mensagens_destinatario_new', type_='foreignkey')
        batch_op.create_foreign_key('fk_mensagens_remetente', 'usuarios', ['remetente_id'], ['id'])
        batch_op.create_foreign_key('fk_mensagens_destinatario', 'usuarios', ['destinatario_id'], ['id'])

    # ### end Alembic commands ###
