"""Add LeituraMensagem model

Revision ID: e7a8ae4aec44
Revises: c9130ded8c73
Create Date: 2025-01-13 16:48:03.454907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a8ae4aec44'
down_revision = 'c9130ded8c73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leituras_mensagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensagem_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('data_leitura', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mensagem_id'], ['mensagens.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leituras_mensagens')
    # ### end Alembic commands ###
