"""Adicionar coluna status_nota na tabela cargas

Revision ID: 54279a565fb1
Revises: 2d64b79598cb
Create Date: 2025-01-23 10:17:28.744889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54279a565fb1'
down_revision = '2d64b79598cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cargas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_status_nota', sa.String(length=50), nullable=True))

    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['remetente_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'usuarios', ['destinatario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'cargas', ['carga_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['solicitado_por_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'usuarios', ['analisado_por_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'usuarios', ['verificado_por_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('senha_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.drop_column('usuario')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('usuario', sa.VARCHAR(length=50), server_default=sa.text("('')"), nullable=False))
        batch_op.alter_column('senha_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['analisado_por_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['solicitado_por_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['verificado_por_id'], ['id'])

    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        batch_op.create_foreign_key(None, 'cargas', ['carga_id'], ['id'])

    with op.batch_alter_table('mensagens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'usuarios', ['remetente_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuarios', ['destinatario_id'], ['id'])

    with op.batch_alter_table('cargas', schema=None) as batch_op:
        batch_op.drop_column('_status_nota')

    # ### end Alembic commands ###
