"""Add chat message fields

Revision ID: c9130ded8c73
Revises: 
Create Date: 2025-01-13 16:37:23.883853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9130ded8c73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_carga')
    op.drop_table('configuracao_formulario')
    op.drop_table('solicitacoes_edicao')
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.alter_column('verificado_em',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes', schema=None) as batch_op:
        batch_op.alter_column('verificado_em',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    op.create_table('solicitacoes_edicao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('carga_id', sa.INTEGER(), nullable=False),
    sa.Column('tipo_solicitacao', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('motivo', sa.VARCHAR(length=500), nullable=True),
    sa.Column('observacoes', sa.VARCHAR(length=500), nullable=True),
    sa.Column('solicitado_por_id', sa.INTEGER(), nullable=False),
    sa.Column('solicitado_em', sa.DATETIME(), nullable=False),
    sa.Column('aprovado_por_id', sa.INTEGER(), nullable=True),
    sa.Column('aprovado_em', sa.DATETIME(), nullable=True),
    sa.Column('verificado_por_id', sa.INTEGER(), nullable=True),
    sa.Column('verificado_em', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['aprovado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['carga_id'], ['cargas.id'], ),
    sa.ForeignKeyConstraint(['solicitado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['verificado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracao_formulario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome_campo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tipo_campo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('obrigatorio', sa.BOOLEAN(), nullable=True),
    sa.Column('ordem', sa.INTEGER(), nullable=True),
    sa.Column('opcoes', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sub_carga',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('carga_id', sa.INTEGER(), nullable=False),
    sa.Column('numero_subcarga', sa.VARCHAR(length=20), nullable=True),
    sa.Column('produtor', sa.VARCHAR(length=100), nullable=True),
    sa.Column('uf_produtor', sa.VARCHAR(length=2), nullable=True),
    sa.Column('numero_nfe', sa.VARCHAR(length=50), nullable=True),
    sa.Column('data_nfe', sa.DATE(), nullable=True),
    sa.Column('numero_gta', sa.VARCHAR(length=50), nullable=True),
    sa.Column('data_gta', sa.DATE(), nullable=True),
    sa.Column('tipo_ave', sa.VARCHAR(length=50), nullable=True),
    sa.Column('criado_em', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['carga_id'], ['cargas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
